backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:

  - name: "theme"
    label: "Theme"
    folder: "src/theme"
    create: false
    slug: "theme"
    fields:
      - {label: "Title", name: "title", widget: 'hidden', default: "Theme"}
      - {label: "Primary Color", name: 'primaryColor', widget: "string"}
      - {label: "Text Color on Primary Color", name: 'primaryColor', widget: "string"}
      - {label: "Secondary Color", name: 'secondaryColor', widget: "string"}
      - {label: "Text Color on Secondary Color", name: 'textOnSecondaryColor', widget: "string"}

  - name: "header"
    label: "Header"
    folder: "src/data"
    create: false
    slug: "header"
    fields:
      - {label: "Title", name: "title", widget: 'hidden', default: "Header"}
      - {label: "Full Name", name: 'fullName', widget: "string"}
      - {label: "Profile Image", name: "profileUrl", widget: 'image'}
      - {label: "[Optional] Short & Snappy Headline", name: 'subtitle', widget: "string"}
      - {label: "[Optional] A Longer bio", name: 'biography', widget: "markdown"}

  - name: "blocks"
    label: "Content Blocks"
    folder: "src/blocks"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}={{day}}"
    fields:
      - label: "Content Type"
        name: 'type'
        widget: "select"
        required: true
        options:
          - {label: "Section Label", value: "sectionLabel"}
          - {label: "Event", value: "event"}
          - {label: "Image Block", value: "image"}
      - {label: "Title", name: "title", widget: 'string', default: "", required: true}
      - {label: "Display Order (Used to order your content blocks)", name: 'order', widget: "number", valueType: "int", required: true}
      - {label: "Display Date (Displayed on the content block)", name: "displayDate", widget: 'string', required: false}
      - {label: "Content", name: 'content', widget: "markdown", required: false}
      - {label: "Image (Only applies to image blocks)", name: "imageURL", widget: 'image'}
      - label: "Image Layout (Only applies to image blocks)"
        name: "imageLayout"
        widget: "select"
        options:
          - {label: "Left Thumbnail", value: "leftThumb"}
          - {label: "Right Thumbnail", value: "rightThumb"}
          - {label: "Full Width", value: "fullWidth"}
