backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter.
    # Remove any that aren't needed for posts
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "theme"
    label: "Theme"
    folder: "src/theme"
    create: false
    slug: "theme"
    fields:
      - {label: "Title", name: "title", widget: 'hidden', default: "Theme"}
      - {label: "Primary Color", name: 'primaryColor', widget: "string"}
      - {label: "Text Color on Primary Color", name: 'primaryColor', widget: "string"}
      - {label: "Secondary Color", name: 'secondaryColor', widget: "string"}
      - {label: "Text Color on Secondary Color", name: 'textOnSecondaryColor', widget: "string"}

  - name: "header"
    label: "Header"
    folder: "src/data"
    create: false
    slug: "header"
    fields:
      - {label: "Title", name: "title", widget: 'hidden', default: "Header"}
      - {label: "Full Name", name: 'fullName', widget: "string"}
      - {label: "Profile Image", name: "profileUrl", widget: 'image'}
      - {label: "[Optional] Short & Snappy Headline", name: 'subtitle', widget: "string"}
      - {label: "[Optional] A Longer bio", name: 'biography', widget: "markdown"}
